### ISSUE TITLE
Week 4 Checkpoint

### ISSUE THREAD

**Issue by Claymays** [Claymays/scorekeeper#2]
@pawaitemadisoncollege I am ready for review of my project!

I struggled quite a bit with writing the project plan. I am sure that there is a thing or two I missed. I would have been well served writing out my own flow for the project, so I could reference that and ensure everything is covered. I will try to do that, and even include a workflow chart on the project for your reference. Unfortunately I have been staring at it for around 10 hours over the last two days, and have to submit what I have for now and try to do better in the future!

**Comment by pawaitemadisoncollege** [comment]
Hi @Claymays! This is a great start on your indie project!  

- [ ] I always like to take an opportunity during checkpoint 1 to compare user stories to the project requirements. I *think* everything is covered except the delete scenario. Is there a meaningful user story that you can think of that would cover the delete case? 
- [ ] Your project plan looks to be well-thought-out and includes a lot of excellent detail. A few things to be aware of that may impact your plan: in week 5 I introduce a generic dao that you are encouraged to use for all tables/entities in your project, we will practice deploying applications using AWS Elastic Beanstalk in week 6, we will practice using Amazon Cognito for authentication in week 7, and in week 8 we'll learn how to consume apis with java code. 
- [ ] The screens page seems to missing images of the screens?
- [ ] The link to the user stories on the readme.md is broken.
- [ ] Remember to mark items completed in your plan when they are done: 
- [X]  Example of complete item

I'm really looking forward to seeing this one built out - its unique!
